Repository Opla/opla, pull requests merged in 2019-03, with the labels that each got.

#225 Update to OpenNLX 0.7.7
  backend/package.json
  backend/yarn.lock
Labels: enhancement

#234 Change green color in action_output class
  front/src/stylesheets/_theming.scss
Labels: enhancement

#233 Fix vulnerability issues related to lodash and momentjs
  e2e/package-lock.json
  front/package.json
  front/yarn.lock
Labels: critical

#232 Load/Save/Demo/Export title
  backend/src/routes/bots.js
  backend/src/utils/importer/index.js
  front/src/shared/actions/api.js
  front/src/shared/actions/constants.js
  front/src/shared/components/dashboardActionbar.jsx
  front/src/shared/components/messengerBox/index.js
  front/src/shared/containers/dashboard.jsx
  front/src/shared/containers/playgroundContainer.jsx
  front/src/shared/reducers/app/index.js
Labels: feature

#230 Disable autocomplete on playground input
  front/src/shared/components/messengerBox/messengerBoxInput.jsx
Labels: enhancement

#236 Redesign factory
  e2e/cypress/integration/opla/add_plugin_messenger_webchat.spec.js
  front/src/shared/components/dashboard/dashboardActionbar.jsx
  front/src/shared/components/dashboard/dashboardDescription.jsx
  front/src/shared/components/dashboard/dashboardExpansionPanel.jsx
  front/src/shared/components/dashboard/dashboardMessagings.jsx
  front/src/shared/components/dashboard/dashboardServiceList.jsx
  front/src/shared/containers/dashboard.jsx
  front/src/shared/containers/dialogs/publishDialog.jsx
  front/src/shared/containers/factory.jsx
  front/src/shared/containers/servicesContainer.jsx
  front/src/shared/opla.js
  front/src/stylesheets/_all.scss
  front/src/stylesheets/_theming.scss
  front/tests/shared/components/dashboard/dashboardMessagings.test.js
Labels: enhancement
